import os

QBO_CONSUMER_KEY = os.environ['QBO_CONSUMER_KEY']
QBO_CONSUMER_SECRET = os.environ['QBO_CONSUMER_SECRET']

GSUITE_CLIENT_ID = os.environ['GSUITE_CLIENT_ID']
GSUITE_CLIENT_SECRET = os.environ['GSUITE_CLIENT_SECRET']
GSUITE_CHARTS_OF_ACCOUNTS_FOLDER_ID = os.environ['GSUITE_CHARTS_OF_ACCOUNTS_FOLDER_ID']
