"""empty message

Revision ID: 0b52632055d0
Revises: 2846af4bcfeb
Create Date: 2016-12-04 19:17:18.745496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b52632055d0'
down_revision = '2846af4bcfeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apply_blueprint_school', sa.Column('match', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apply_blueprint_school', 'match')
    # ### end Alembic commands ###
