"""empty message

Revision ID: 21b8b59a1e9f
Revises: e40b98b48587
Create Date: 2017-04-12 10:19:48.411063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b8b59a1e9f'
down_revision = 'e40b98b48587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'apply_blueprint_school', 'parent_observation_optional')
    op.drop_column(u'apply_blueprint_school', 'parent_teacher_conversation_optional')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'apply_blueprint_school', sa.Column('parent_teacher_conversation_optional', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column(u'apply_blueprint_school', sa.Column('parent_observation_optional', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
