"""empty message

Revision ID: 21b8b59a1e9f
Revises: e40b98b48587
Create Date: 2017-04-12 10:19:48.411063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b8b59a1e9f'
down_revision = 'e40b98b48587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_public_directory_blueprint_directory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('slack_id', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('img_url', sa.String(length=120), nullable=True),
    sa.Column('link_url', sa.String(length=120), nullable=True),
    sa.Column('link_text', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'apply_blueprint_school', 'parent_observation_optional')
    op.drop_column(u'apply_blueprint_school', 'parent_teacher_conversation_optional')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'apply_blueprint_school', sa.Column('parent_teacher_conversation_optional', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column(u'apply_blueprint_school', sa.Column('parent_observation_optional', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('slack_public_directory_blueprint_directory')
    # ### end Alembic commands ###
