"""empty message

Revision ID: 253a53827eed
Revises: dfb1b9029365
Create Date: 2017-01-12 14:01:48.380483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253a53827eed'
down_revision = 'dfb1b9029365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apply_blueprint_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apply_blueprint_email_school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['apply_blueprint_email.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['apply_blueprint_school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apply_blueprint_email_school')
    op.drop_table('apply_blueprint_email')
    # ### end Alembic commands ###
