"""empty message

Revision ID: 2846af4bcfeb
Revises:
Create Date: 2016-12-02 15:05:30.164736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2846af4bcfeb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apply_blueprint_school',
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('schedule_interview_url', sa.String(length=80), nullable=True),
    sa.Column('schedule_observation_url', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('survey_monkey_choice_id', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apply_blueprint_checklist',
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('interview_scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('observation_scheduled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['apply_blueprint_school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apply_blueprint_checklist')
    op.drop_table('apply_blueprint_school')
    # ### end Alembic commands ###
