"""empty message

Revision ID: 3ed77ef207dc
Revises: 0b52632055d0
Create Date: 2016-12-09 09:14:55.771565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed77ef207dc'
down_revision = '0b52632055d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apply_blueprint_checklist', sa.Column('visit_scheduled_at', sa.DateTime(), nullable=True))
    op.add_column('apply_blueprint_school', sa.Column('interview_optional', sa.Boolean(), nullable=True))
    op.add_column('apply_blueprint_school', sa.Column('observation_optional', sa.Boolean(), nullable=True))
    op.add_column('apply_blueprint_school', sa.Column('schedule_visit_url', sa.String(length=120), nullable=True))
    op.add_column('apply_blueprint_school', sa.Column('visit_optional', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apply_blueprint_school', 'visit_optional')
    op.drop_column('apply_blueprint_school', 'schedule_visit_url')
    op.drop_column('apply_blueprint_school', 'observation_optional')
    op.drop_column('apply_blueprint_school', 'interview_optional')
    op.drop_column('apply_blueprint_checklist', 'visit_scheduled_at')
    # ### end Alembic commands ###
