"""empty message

Revision ID: 41d068234c8a
Revises: 21b8b59a1e9f
Create Date: 2017-04-12 11:16:48.790083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41d068234c8a'
down_revision = '21b8b59a1e9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_profiles_blueprint_public_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('slack_id', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('img_url', sa.String(length=120), nullable=True),
    sa.Column('link_url', sa.String(length=120), nullable=True),
    sa.Column('link_text', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('public_profiles_blueprint_public_profile')
    # ### end Alembic commands ###
