"""empty message

Revision ID: 5ac48b12814e
Revises: 78ea25ffe628
Create Date: 2017-01-05 11:06:04.901784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ac48b12814e'
down_revision = '78ea25ffe628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apply_blueprint_checklist', sa.Column('child_visit_scheduled_at', sa.DateTime(), nullable=True))
    op.add_column('apply_blueprint_checklist', sa.Column('parent_observation_scheduled_at', sa.DateTime(), nullable=True))
    op.add_column('apply_blueprint_checklist', sa.Column('parent_teacher_conversation_scheduled_at', sa.DateTime(), nullable=True))
    op.drop_column('apply_blueprint_checklist', 'interview_scheduled_at')
    op.drop_column('apply_blueprint_checklist', 'observation_scheduled_at')
    op.drop_column('apply_blueprint_checklist', 'visit_scheduled_at')
    op.add_column('apply_blueprint_school', sa.Column('child_visit_optional', sa.Boolean(), nullable=True))
    op.add_column('apply_blueprint_school', sa.Column('parent_observation_optional', sa.Boolean(), nullable=True))
    op.add_column('apply_blueprint_school', sa.Column('parent_teacher_conversation_optional', sa.Boolean(), nullable=True))
    op.add_column('apply_blueprint_school', sa.Column('schedule_child_visit_url', sa.String(length=80), nullable=True))
    op.add_column('apply_blueprint_school', sa.Column('schedule_parent_observation_url', sa.String(length=80), nullable=True))
    op.add_column('apply_blueprint_school', sa.Column('schedule_parent_teacher_conversation_url', sa.String(length=80), nullable=True))
    op.drop_column('apply_blueprint_school', 'schedule_visit_url')
    op.drop_column('apply_blueprint_school', 'observation_optional')
    op.drop_column('apply_blueprint_school', 'interview_optional')
    op.drop_column('apply_blueprint_school', 'visit_optional')
    op.drop_column('apply_blueprint_school', 'schedule_interview_url')
    op.drop_column('apply_blueprint_school', 'schedule_observation_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apply_blueprint_school', sa.Column('schedule_observation_url', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('apply_blueprint_school', sa.Column('schedule_interview_url', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('apply_blueprint_school', sa.Column('visit_optional', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('apply_blueprint_school', sa.Column('interview_optional', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('apply_blueprint_school', sa.Column('observation_optional', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('apply_blueprint_school', sa.Column('schedule_visit_url', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('apply_blueprint_school', 'schedule_parent_teacher_conversation_url')
    op.drop_column('apply_blueprint_school', 'schedule_parent_observation_url')
    op.drop_column('apply_blueprint_school', 'schedule_child_visit_url')
    op.drop_column('apply_blueprint_school', 'parent_teacher_conversation_optional')
    op.drop_column('apply_blueprint_school', 'parent_observation_optional')
    op.drop_column('apply_blueprint_school', 'child_visit_optional')
    op.add_column('apply_blueprint_checklist', sa.Column('visit_scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('apply_blueprint_checklist', sa.Column('observation_scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('apply_blueprint_checklist', sa.Column('interview_scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('apply_blueprint_checklist', 'parent_teacher_conversation_scheduled_at')
    op.drop_column('apply_blueprint_checklist', 'parent_observation_scheduled_at')
    op.drop_column('apply_blueprint_checklist', 'child_visit_scheduled_at')
    # ### end Alembic commands ###
