"""empty message

Revision ID: 60b3f66b41fe
Revises: 7705257eb078
Create Date: 2017-05-04 11:47:28.659197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b3f66b41fe'
down_revision = '7705257eb078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apply_blueprint_school', 'email_parent_template')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apply_blueprint_school', sa.Column('email_parent_template', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
