"""empty message

Revision ID: 7705257eb078
Revises: 463df56e7400
Create Date: 2017-04-18 08:32:32.561689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7705257eb078'
down_revision = '463df56e7400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('public_profiles_blueprint_public_profile', sa.Column('bio', sa.String(length=256), nullable=True))
    op.drop_column('public_profiles_blueprint_public_profile', 'link_url')
    op.drop_column('public_profiles_blueprint_public_profile', 'link_text')
    op.alter_column('public_profiles_blueprint_public_profile', 'img_url', type_=sa.String(length=256))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('public_profiles_blueprint_public_profile', sa.Column('link_text', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('public_profiles_blueprint_public_profile', sa.Column('link_url', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('public_profiles_blueprint_public_profile', 'bio')
    op.alter_column('public_profiles_blueprint_public_profile', 'img_url', type_=sa.String(length=240))
    # ### end Alembic commands ###
