"""empty message

Revision ID: 78ea25ffe628
Revises: 3ed77ef207dc
Create Date: 2016-12-13 10:32:14.969567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ea25ffe628'
down_revision = '3ed77ef207dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apply_school', 'survey_monkey_choice_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apply_school', sa.Column('survey_monkey_choice_id', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
