"""empty message

Revision ID: b48f88539d7e
Revises: 60b3f66b41fe
Create Date: 2017-06-09 10:56:42.885623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48f88539d7e'
down_revision = '60b3f66b41fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qbo_blueprint_authentication_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('oauth_token', sa.String(length=120), nullable=True),
    sa.Column('oauth_token_secret', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qbo_blueprint_authentication_tokens')
    # ### end Alembic commands ###
