"""empty message

Revision ID: e40b98b48587
Revises: be1b1633fc24
Create Date: 2017-02-10 13:03:44.003175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40b98b48587'
down_revision = 'be1b1633fc24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apply_blueprint_school', sa.Column('email_parent_template', sa.String(length=120), nullable=True))
    op.drop_column('apply_blueprint_school', 'schedule_child_visit_url')
    op.drop_column('apply_blueprint_school', 'child_visit_optional')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apply_blueprint_school', sa.Column('child_visit_optional', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('apply_blueprint_school', sa.Column('schedule_child_visit_url', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('apply_blueprint_school', 'email_parent_template')
    # ### end Alembic commands ###
