"""empty message

Revision ID: e716026b822f
Revises: 5ac48b12814e
Create Date: 2017-01-05 11:30:59.098153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e716026b822f'
down_revision = '5ac48b12814e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apply_blueprint_school', sa.Column('tc_school_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apply_blueprint_school', 'tc_school_id')
    # ### end Alembic commands ###
