import os

DEBUG=False
SQLALCHEMY_TRACK_MODIFICATIONS=False

SURVEY_MONKEY_OAUTH_TOKEN=os.environ['SURVEY_MONKEY_OAUTH_TOKEN']
SURVEY_MONKEY_SURVEY_ID='111419034'
SURVEY_MONKEY_COLLECTOR_ID='FQDVNM3'
SURVEY_MONKEY_WHICH_SCHOOLS_QUESTION_ID='69085210'
